name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: sample
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
      - name: Cache vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
      - name: Build
        run: composer install
      - name: Lint
        run: composer lint
      - name: DB migrate
        run: composer migration:test
      - name: Run test
        run: composer test
      - name: Archive coverage results
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: coverage-report
          path: coverage
